name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Check out code
      uses: actions/checkout@v2

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install poetry
      run: pip install poetry==1.5.1

    - name: Install dependencies
      run: poetry install --no-root

    - name: Run unit tests
      run: PYTHONPATH=tidal_algorithmic_mixes:test poetry run pytest test/
